function generateHTML(type) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Generated by CODAI UNICK</title>
</head>
<body>
  <h1>Hello from Constance AI</h1>
  <p>This HTML was generated automatically.</p>
</body>
</html>
`;
}
