function generateCode() {
  const prompt = document.getElementById("prompt").value.toLowerCase();
  const lang = document.getElementById("language").value;
  const uiLang = document.getElementById("uiLang").value;
  const out = document.getElementById("output");

  const header = uiLang === "fr"
    ? "// Code généré par Constance AI 🇹🇬\n\n"
    : "// Code generated by Constance AI 🇹🇬\n\n";

  let code = "";

  if (lang === "verilog") {
    if (prompt.includes("addition")) code = verilogAdder();
    else if (prompt.includes("compteur")) code = verilogCounter();
    else code = verilogBase();
  }

  if (lang === "vhdl") code = vhdlBase();
  if (lang === "arduino") code = arduinoBase();
  if (lang === "cpp") code = cppBase();
  if (lang === "html") code = htmlBase();

  out.textContent = header + code;
}

function copyCode() {
  navigator.clipboard.writeText(
    document.getElementById("output").textContent
  );
  alert("Code copied");
}

function exportFile() {
  const lang = document.getElementById("language").value;
  const content = document.getElementById("output").textContent;

  const ext = {
    verilog: "v",
    vhdl: "vhd",
    arduino: "ino",
    cpp: "cpp",
    html: "html"
  }[lang];

  const blob = new Blob([content], { type: "text/plain" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = `codai_unick.${ext}`;
  a.click();
}

function upload() {
  alert(
    "Upload instructions:\n\n" +
    "• FPGA: Vivado / Quartus\n" +
    "• Arduino: Arduino IDE\n" +
    "• C++: g++ / PlatformIO\n\n" +
    "Export the file, then upload to your board."
  );
}

/* ===== CODE GENERATORS ===== */

function verilogBase() {
return `
module top(input wire a, input wire b, output wire y);
  assign y = a & b;
endmodule
`;
}

function verilogAdder() {
return `
module adder(input [7:0] a, b, output [8:0] sum);
  assign sum = a + b;
endmodule
`;
}

function verilogCounter() {
return `
module counter(input clk, output reg [3:0] count);
  always @(posedge clk)
    count <= count + 1;
endmodule
`;
}

function vhdlBase() {
return `
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity top is
  Port ( a,b : in STD_LOGIC; y : out STD_LOGIC );
end top;

architecture Behavioral of top is
begin
  y <= a and b;
end Behavioral;
`;
}

function arduinoBase() {
return `
void setup() {
  pinMode(13, OUTPUT);
}

void loop() {
  digitalWrite(13, HIGH);
  delay(500);
  digitalWrite(13, LOW);
  delay(500);
}
`;
}

function cppBase() {
return `
#include <iostream>
int main() {
  std::cout << "Generated by Constance AI";
  return 0;
}
`;
}

function htmlBase() {
return `
<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      background:black;
      color:red;
      text-align:center;
      padding-top:40px;
      font-family:Arial;
    }
  </style>
</head>
<body>
  <h1>Hello from Constance AI</h1>
</body>
</html>
`;
}
