// CODAI UNICK – Main App Controller
// v1.0 Stable

// generateCode() is defined in constance.js
// This file is intentionally minimal

console.log("CODAI UNICK v1.0 loaded successfully");
function copyCode() {
  const code = document.getElementById("code");
  code.select();
  document.execCommand("copy");
  alert("Code copied to clipboard ✅");
}

function uploadHelp() {
  alert(
    "To upload the code:\n\n" +
    "- Arduino: open Arduino IDE, paste, upload\n" +
    "- FPGA: use Vivado / Quartus with generated files\n\n" +
    "CODAI UNICK generates the code.\nYou stay in control of the hardware."
  );
}function generateVerilog(prompt) {
  return `
module example (
  input wire clk,
  input wire a,
  input wire b,
  output wire y
);
  assign y = a & b;
endmodule
`;
}

function generateVHDL() {
  return `
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity example is
  Port ( a : in STD_LOGIC;
         b : in STD_LOGIC;
         y : out STD_LOGIC);
end example;

architecture Behavioral of example is
begin
  y <= a and b;
end Behavioral;
`;
}

function generateArduino() {
  return `
void setup() {
  pinMode(13, OUTPUT);
}

void loop() {
  digitalWrite(13, HIGH);
  delay(500);
  digitalWrite(13, LOW);
  delay(500);
}
`;
}

function generateCpp() {
  return `
#include <iostream>
using namespace std;

int main() {
  cout << "Hello from Constance AI" << endl;
  return 0;
}
`;
}

function generateHTML() {
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Generated by Constance AI</title>
  <style>
    body {
      background: black;
      color: red;
      font-family: Arial;
      text-align: center;
      padding-top: 40px;
    }
    button {
      background: red;
      color: white;
      border: none;
      padding: 10px 20px;
      border-radius: 8px;
    }
  </style>
</head>
<body>
  <h1>Hello World</h1>
  <button>Click me</button>
</body>
</html>
`;
}
