function generate() {
  const prompt = document.getElementById("prompt").value.toLowerCase();
  const language = document.getElementById("language").value;
  const output = document.getElementById("output");

  output.textContent = "🧠 Constance AI is thinking...\n";

  setTimeout(() => {
    let code = "";
    let intro = "";

    const isFrench = prompt.includes("je") || prompt.includes("carte") || prompt.includes("fpga");

    if (isFrench) {
      intro = "// Code généré par Constance AI (FR)\n";
    } else {
      intro = "// Code generated by Constance AI (EN)\n";
    }

    switch (language) {
      case "Verilog":
        code = intro + generateVerilog(prompt);
        break;

      case "VHDL":
        code = intro + generateVHDL();
        break;

      case "Arduino":
        code = intro + generateArduino();
        break;

      case "C++":
        code = intro + generateCpp();
        break;

      case "HTML":
        code = intro + generateHTML();
        break;

      default:
        code = "// Unsupported language";
    }

    output.textContent = code;
  }, 900);
}
